name: Atlas Lint

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      latest:
        description: Number of latest migration files to lint
        default: "1"

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ariga/setup-atlas@v0
        with:
          cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
      - name: Hash migrations
        run: atlas migrate hash --dir file://migrations
      - name: Lint migrations
        run: |
          atlas migrate lint \
            --dir file://migrations \
            --dev-url "sqlite://dev?mode=memory" \
            --latest ${{ inputs.latest || '1' }}
